# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 百度极速版3

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
  repository_dispatch:
        types: baidu_speed3        
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      BAIDU_COOKIE3: ${{ secrets.BAIDU_COOKIE3 }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【百度极速版3】'
        if: env.BAIDU_COOKIE3
        run: |
          node baidu_speed3.js
        env:
          BAIDU_COOKIE3: ${{ secrets.BAIDU_COOKIE3 }}  
