name: 步步宝

workflow_dispatch:
    schedule:
     - cron: "0 0-14/2 * * *"
  watch:
        types: [started]
   
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"
      # 安装依赖包
      - name: 安装依赖包
        run: npm install
        
      - name: '运行步步宝脚本'  
        run: node BBB_Task.js
        env:
          BBB_COOKIE: ${{ secrets.BBB_COOKIE }}
